// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/example"
	mock "github.com/stretchr/testify/mock"
)

// NewMockExampleProvisioner creates a new instance of MockExampleProvisioner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockExampleProvisioner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockExampleProvisioner {
	mock := &MockExampleProvisioner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockExampleProvisioner is an autogenerated mock type for the ExampleProvisioner type
type MockExampleProvisioner struct {
	mock.Mock
}

type MockExampleProvisioner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockExampleProvisioner) EXPECT() *MockExampleProvisioner_Expecter {
	return &MockExampleProvisioner_Expecter{mock: &_m.Mock}
}

// Provision provides a mock function for the type MockExampleProvisioner
func (_mock *MockExampleProvisioner) Provision(ctx context.Context, id example.ExampleID, name string) error {
	ret := _mock.Called(ctx, id, name)

	if len(ret) == 0 {
		panic("no return value specified for Provision")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, example.ExampleID, string) error); ok {
		r0 = returnFunc(ctx, id, name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockExampleProvisioner_Provision_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Provision'
type MockExampleProvisioner_Provision_Call struct {
	*mock.Call
}

// Provision is a helper method to define mock.On call
//   - ctx context.Context
//   - id example.ExampleID
//   - name string
func (_e *MockExampleProvisioner_Expecter) Provision(ctx any, id any, name any) *MockExampleProvisioner_Provision_Call {
	return &MockExampleProvisioner_Provision_Call{Call: _e.mock.On("Provision", ctx, id, name)}
}

func (_c *MockExampleProvisioner_Provision_Call) Run(run func(ctx context.Context, id example.ExampleID, name string)) *MockExampleProvisioner_Provision_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 example.ExampleID
		if args[1] != nil {
			arg1 = args[1].(example.ExampleID)
		}
		var arg2 string
		if args[2] != nil {
			arg2 = args[2].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockExampleProvisioner_Provision_Call) Return(err error) *MockExampleProvisioner_Provision_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockExampleProvisioner_Provision_Call) RunAndReturn(run func(ctx context.Context, id example.ExampleID, name string) error) *MockExampleProvisioner_Provision_Call {
	_c.Call.Return(run)
	return _c
}
