version: '3.8'

services:
  hosttask:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: host_task
    ports:
      - "8080:8080"
    restart: unless-stopped

  autohealing:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: auto_healing
    ports:
      - "8081:8080"
    restart: unless-stopped

  hostmanager:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: host_manager
    ports:
      - "8082:8080"
    restart: unless-stopped

  scenario:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: scenario
    ports:
      - "8083:8080"
    restart: unless-stopped

  audiologs:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVICE: audio_logs
    ports:
      - "8084:8080"
    restart: unless-stopped