// Code generated by go-enum DO NOT EDIT.
// Version:
// Revision:
// Build Date:
// Built By:

package entities

import (
	"database/sql/driver"
	"errors"
	"fmt"

	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/bsontype"
	"go.mongodb.org/mongo-driver/x/bsonx/bsoncore"
)

const (
	// HostKindUnknown is a HostKind of type Unknown.
	HostKindUnknown HostKind = iota
	// HostKindServer is a HostKind of type Server.
	HostKindServer
	// HostKindMac is a HostKind of type Mac.
	HostKindMac
)

var ErrInvalidHostKind = errors.New("not a valid HostKind")

const _HostKindName = "unknownservermac"

var _HostKindMap = map[HostKind]string{
	HostKindUnknown: _HostKindName[0:7],
	HostKindServer:  _HostKindName[7:13],
	HostKindMac:     _HostKindName[13:16],
}

// String implements the Stringer interface.
func (x HostKind) String() string {
	if str, ok := _HostKindMap[x]; ok {
		return str
	}
	return fmt.Sprintf("HostKind(%d)", x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x HostKind) IsValid() bool {
	_, ok := _HostKindMap[x]
	return ok
}

var _HostKindValue = map[string]HostKind{
	_HostKindName[0:7]:   HostKindUnknown,
	_HostKindName[7:13]:  HostKindServer,
	_HostKindName[13:16]: HostKindMac,
}

// ParseHostKind attempts to convert a string to a HostKind.
func ParseHostKind(name string) (HostKind, error) {
	if x, ok := _HostKindValue[name]; ok {
		return x, nil
	}
	return HostKind(0), fmt.Errorf("%s is %w", name, ErrInvalidHostKind)
}

// MarshalText implements the text marshaller method.
func (x HostKind) MarshalText() ([]byte, error) {
	return []byte(x.String()), nil
}

// UnmarshalText implements the text unmarshaller method.
func (x *HostKind) UnmarshalText(text []byte) error {
	name := string(text)
	tmp, err := ParseHostKind(name)
	if err != nil {
		return err
	}
	*x = tmp
	return nil
}

// MarshalBSONValue implements the bson.ValueMarshaler method.
func (x HostKind) MarshalBSONValue() (bsontype.Type, []byte, error) {
	return bson.TypeString, bsoncore.AppendString([]byte{}, x.String()), nil
}

// UnmarshalBSONValue implements the bson.ValueUnmarshaler method.
func (x *HostKind) UnmarshalBSONValue(t bsontype.Type, src []byte) (err error) {
	switch t {
	case bson.TypeString:
		res, _, ok := bsoncore.ReadString(src)
		if !ok {
			return fmt.Errorf("error reading string from bson")
		}
		*x, err = ParseHostKind(res)
	case bson.TypeInt32:
		res, _, ok := bsoncore.ReadInt32(src)
		if !ok {
			return fmt.Errorf("error reading int32 from bson")
		}
		*x = HostKind(res)
	case bson.TypeInt64:
		res, _, ok := bsoncore.ReadInt64(src)
		if !ok {
			return fmt.Errorf("error reading int64 from bson")
		}
		*x = HostKind(res)
	}
	return
}

var errHostKindNilPtr = errors.New("value pointer is nil") // one per type for package clashes

// Scan implements the Scanner interface.
func (x *HostKind) Scan(value interface{}) (err error) {
	if value == nil {
		*x = HostKind(0)
		return
	}

	// A wider range of scannable types.
	// driver.Value values at the top of the list for expediency
	switch v := value.(type) {
	case int64:
		*x = HostKind(v)
	case int32:
		*x = HostKind(v)
	case int16:
		*x = HostKind(v)
	case int8:
		*x = HostKind(v)
	case string:
		*x, err = ParseHostKind(v)
	case []byte:
		*x, err = ParseHostKind(string(v))
	case HostKind:
		*x = v
	case int:
		*x = HostKind(v)
	case *HostKind:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = *v
	case uint:
		*x = HostKind(v)
	case uint64:
		*x = HostKind(v)
	case uint32:
		*x = HostKind(v)
	case uint16:
		*x = HostKind(v)
	case uint8:
		*x = HostKind(v)
	case *int:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *int64:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *int32:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *int16:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *int8:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case float64: // json marshals everything as a float64 if it's a number
		*x = HostKind(v)
	case *float64: // json marshals everything as a float64 if it's a number
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *uint:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *uint64:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *uint32:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *uint16:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *uint8:
		if v == nil {
			return errHostKindNilPtr
		}
		*x = HostKind(*v)
	case *string:
		if v == nil {
			return errHostKindNilPtr
		}
		*x, err = ParseHostKind(*v)
	}

	return
}

// Value implements the driver Valuer interface.
func (x HostKind) Value() (driver.Value, error) {
	return x.String(), nil
}
