// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockActiveHostByFQDN creates a new instance of MockActiveHostByFQDN. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockActiveHostByFQDN(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockActiveHostByFQDN {
	mock := &MockActiveHostByFQDN{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockActiveHostByFQDN is an autogenerated mock type for the ActiveHostByFQDN type
type MockActiveHostByFQDN struct {
	mock.Mock
}

type MockActiveHostByFQDN_Expecter struct {
	mock *mock.Mock
}

func (_m *MockActiveHostByFQDN) EXPECT() *MockActiveHostByFQDN_Expecter {
	return &MockActiveHostByFQDN_Expecter{mock: &_m.Mock}
}

// ActiveHostByFQDN provides a mock function for the type MockActiveHostByFQDN
func (_mock *MockActiveHostByFQDN) ActiveHostByFQDN(ctx context.Context, fqdn string) (domain.HostID, bool, error) {
	ret := _mock.Called(ctx, fqdn)

	if len(ret) == 0 {
		panic("no return value specified for ActiveHostByFQDN")
	}

	var r0 domain.HostID
	var r1 bool
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (domain.HostID, bool, error)); ok {
		return returnFunc(ctx, fqdn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) domain.HostID); ok {
		r0 = returnFunc(ctx, fqdn)
	} else {
		r0 = ret.Get(0).(domain.HostID)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) bool); ok {
		r1 = returnFunc(ctx, fqdn)
	} else {
		r1 = ret.Get(1).(bool)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, string) error); ok {
		r2 = returnFunc(ctx, fqdn)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockActiveHostByFQDN_ActiveHostByFQDN_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ActiveHostByFQDN'
type MockActiveHostByFQDN_ActiveHostByFQDN_Call struct {
	*mock.Call
}

// ActiveHostByFQDN is a helper method to define mock.On call
//   - ctx context.Context
//   - fqdn string
func (_e *MockActiveHostByFQDN_Expecter) ActiveHostByFQDN(ctx any, fqdn any) *MockActiveHostByFQDN_ActiveHostByFQDN_Call {
	return &MockActiveHostByFQDN_ActiveHostByFQDN_Call{Call: _e.mock.On("ActiveHostByFQDN", ctx, fqdn)}
}

func (_c *MockActiveHostByFQDN_ActiveHostByFQDN_Call) Run(run func(ctx context.Context, fqdn string)) *MockActiveHostByFQDN_ActiveHostByFQDN_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockActiveHostByFQDN_ActiveHostByFQDN_Call) Return(existing domain.HostID, found bool, err error) *MockActiveHostByFQDN_ActiveHostByFQDN_Call {
	_c.Call.Return(existing, found, err)
	return _c
}

func (_c *MockActiveHostByFQDN_ActiveHostByFQDN_Call) RunAndReturn(run func(ctx context.Context, fqdn string) (domain.HostID, bool, error)) *MockActiveHostByFQDN_ActiveHostByFQDN_Call {
	_c.Call.Return(run)
	return _c
}
