// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockDCRepository creates a new instance of MockDCRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockDCRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockDCRepository {
	mock := &MockDCRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockDCRepository is an autogenerated mock type for the DCRepository type
type MockDCRepository struct {
	mock.Mock
}

type MockDCRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockDCRepository) EXPECT() *MockDCRepository_Expecter {
	return &MockDCRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockDCRepository
func (_mock *MockDCRepository) Delete(ctx context.Context, id domain.DCID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DCID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDCRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockDCRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.DCID
func (_e *MockDCRepository_Expecter) Delete(ctx any, id any) *MockDCRepository_Delete_Call {
	return &MockDCRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockDCRepository_Delete_Call) Run(run func(ctx context.Context, id domain.DCID)) *MockDCRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DCID
		if args[1] != nil {
			arg1 = args[1].(domain.DCID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDCRepository_Delete_Call) Return(err error) *MockDCRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDCRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.DCID) error) *MockDCRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockDCRepository
func (_mock *MockDCRepository) Load(ctx context.Context, id domain.DCID) (*domain.DC, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *domain.DC
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DCID) (*domain.DC, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.DCID) *domain.DC); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.DC)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.DCID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockDCRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockDCRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.DCID
func (_e *MockDCRepository_Expecter) Load(ctx any, id any) *MockDCRepository_Load_Call {
	return &MockDCRepository_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockDCRepository_Load_Call) Run(run func(ctx context.Context, id domain.DCID)) *MockDCRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.DCID
		if args[1] != nil {
			arg1 = args[1].(domain.DCID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDCRepository_Load_Call) Return(dC *domain.DC, err error) *MockDCRepository_Load_Call {
	_c.Call.Return(dC, err)
	return _c
}

func (_c *MockDCRepository_Load_Call) RunAndReturn(run func(ctx context.Context, id domain.DCID) (*domain.DC, error)) *MockDCRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockDCRepository
func (_mock *MockDCRepository) Save(ctx context.Context, dc *domain.DC) error {
	ret := _mock.Called(ctx, dc)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.DC) error); ok {
		r0 = returnFunc(ctx, dc)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockDCRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockDCRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - dc *domain.DC
func (_e *MockDCRepository_Expecter) Save(ctx any, dc any) *MockDCRepository_Save_Call {
	return &MockDCRepository_Save_Call{Call: _e.mock.On("Save", ctx, dc)}
}

func (_c *MockDCRepository_Save_Call) Run(run func(ctx context.Context, dc *domain.DC)) *MockDCRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.DC
		if args[1] != nil {
			arg1 = args[1].(*domain.DC)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockDCRepository_Save_Call) Return(err error) *MockDCRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockDCRepository_Save_Call) RunAndReturn(run func(ctx context.Context, dc *domain.DC) error) *MockDCRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
