// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHostsInProject creates a new instance of MockHostsInProject. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostsInProject(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostsInProject {
	mock := &MockHostsInProject{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHostsInProject is an autogenerated mock type for the HostsInProject type
type MockHostsInProject struct {
	mock.Mock
}

type MockHostsInProject_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostsInProject) EXPECT() *MockHostsInProject_Expecter {
	return &MockHostsInProject_Expecter{mock: &_m.Mock}
}

// HostsInProject provides a mock function for the type MockHostsInProject
func (_mock *MockHostsInProject) HostsInProject(ctx context.Context, id domain.ProjectID) (int, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for HostsInProject")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProjectID) (int, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ProjectID) int); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ProjectID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostsInProject_HostsInProject_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HostsInProject'
type MockHostsInProject_HostsInProject_Call struct {
	*mock.Call
}

// HostsInProject is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ProjectID
func (_e *MockHostsInProject_Expecter) HostsInProject(ctx any, id any) *MockHostsInProject_HostsInProject_Call {
	return &MockHostsInProject_HostsInProject_Call{Call: _e.mock.On("HostsInProject", ctx, id)}
}

func (_c *MockHostsInProject_HostsInProject_Call) Run(run func(ctx context.Context, id domain.ProjectID)) *MockHostsInProject_HostsInProject_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ProjectID
		if args[1] != nil {
			arg1 = args[1].(domain.ProjectID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostsInProject_HostsInProject_Call) Return(n int, err error) *MockHostsInProject_HostsInProject_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockHostsInProject_HostsInProject_Call) RunAndReturn(run func(ctx context.Context, id domain.ProjectID) (int, error)) *MockHostsInProject_HostsInProject_Call {
	_c.Call.Return(run)
	return _c
}
