// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockHostRepository creates a new instance of MockHostRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHostRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHostRepository {
	mock := &MockHostRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHostRepository is an autogenerated mock type for the HostRepository type
type MockHostRepository struct {
	mock.Mock
}

type MockHostRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHostRepository) EXPECT() *MockHostRepository_Expecter {
	return &MockHostRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockHostRepository
func (_mock *MockHostRepository) Delete(ctx context.Context, id domain.HostID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HostID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockHostRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.HostID
func (_e *MockHostRepository_Expecter) Delete(ctx any, id any) *MockHostRepository_Delete_Call {
	return &MockHostRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockHostRepository_Delete_Call) Run(run func(ctx context.Context, id domain.HostID)) *MockHostRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HostID
		if args[1] != nil {
			arg1 = args[1].(domain.HostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostRepository_Delete_Call) Return(err error) *MockHostRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.HostID) error) *MockHostRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockHostRepository
func (_mock *MockHostRepository) Load(ctx context.Context, id domain.HostID) (*domain.Host, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *domain.Host
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HostID) (*domain.Host, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.HostID) *domain.Host); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Host)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.HostID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHostRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockHostRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.HostID
func (_e *MockHostRepository_Expecter) Load(ctx any, id any) *MockHostRepository_Load_Call {
	return &MockHostRepository_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockHostRepository_Load_Call) Run(run func(ctx context.Context, id domain.HostID)) *MockHostRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.HostID
		if args[1] != nil {
			arg1 = args[1].(domain.HostID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostRepository_Load_Call) Return(host *domain.Host, err error) *MockHostRepository_Load_Call {
	_c.Call.Return(host, err)
	return _c
}

func (_c *MockHostRepository_Load_Call) RunAndReturn(run func(ctx context.Context, id domain.HostID) (*domain.Host, error)) *MockHostRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockHostRepository
func (_mock *MockHostRepository) Save(ctx context.Context, h *domain.Host) error {
	ret := _mock.Called(ctx, h)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Host) error); ok {
		r0 = returnFunc(ctx, h)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHostRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockHostRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - h *domain.Host
func (_e *MockHostRepository_Expecter) Save(ctx any, h any) *MockHostRepository_Save_Call {
	return &MockHostRepository_Save_Call{Call: _e.mock.On("Save", ctx, h)}
}

func (_c *MockHostRepository_Save_Call) Run(run func(ctx context.Context, h *domain.Host)) *MockHostRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Host
		if args[1] != nil {
			arg1 = args[1].(*domain.Host)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockHostRepository_Save_Call) Return(err error) *MockHostRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHostRepository_Save_Call) RunAndReturn(run func(ctx context.Context, h *domain.Host) error) *MockHostRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
