// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockIDGenerator creates a new instance of MockIDGenerator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockIDGenerator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockIDGenerator {
	mock := &MockIDGenerator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockIDGenerator is an autogenerated mock type for the IDGenerator type
type MockIDGenerator struct {
	mock.Mock
}

type MockIDGenerator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockIDGenerator) EXPECT() *MockIDGenerator_Expecter {
	return &MockIDGenerator_Expecter{mock: &_m.Mock}
}

// NewID provides a mock function for the type MockIDGenerator
func (_mock *MockIDGenerator) NewID() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for NewID")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockIDGenerator_NewID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'NewID'
type MockIDGenerator_NewID_Call struct {
	*mock.Call
}

// NewID is a helper method to define mock.On call
func (_e *MockIDGenerator_Expecter) NewID() *MockIDGenerator_NewID_Call {
	return &MockIDGenerator_NewID_Call{Call: _e.mock.On("NewID")}
}

func (_c *MockIDGenerator_NewID_Call) Run(run func()) *MockIDGenerator_NewID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockIDGenerator_NewID_Call) Return(s string) *MockIDGenerator_NewID_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockIDGenerator_NewID_Call) RunAndReturn(run func() string) *MockIDGenerator_NewID_Call {
	_c.Call.Return(run)
	return _c
}
