// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockMatchAdvisor creates a new instance of MockMatchAdvisor. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockMatchAdvisor(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockMatchAdvisor {
	mock := &MockMatchAdvisor{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockMatchAdvisor is an autogenerated mock type for the MatchAdvisor type
type MockMatchAdvisor struct {
	mock.Mock
}

type MockMatchAdvisor_Expecter struct {
	mock *mock.Mock
}

func (_m *MockMatchAdvisor) EXPECT() *MockMatchAdvisor_Expecter {
	return &MockMatchAdvisor_Expecter{mock: &_m.Mock}
}

// Candidates provides a mock function for the type MockMatchAdvisor
func (_mock *MockMatchAdvisor) Candidates(ctx context.Context, fqdn string) ([]domain.HostID, error) {
	ret := _mock.Called(ctx, fqdn)

	if len(ret) == 0 {
		panic("no return value specified for Candidates")
	}

	var r0 []domain.HostID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) ([]domain.HostID, error)); ok {
		return returnFunc(ctx, fqdn)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) []domain.HostID); ok {
		r0 = returnFunc(ctx, fqdn)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]domain.HostID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, fqdn)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockMatchAdvisor_Candidates_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Candidates'
type MockMatchAdvisor_Candidates_Call struct {
	*mock.Call
}

// Candidates is a helper method to define mock.On call
//   - ctx context.Context
//   - fqdn string
func (_e *MockMatchAdvisor_Expecter) Candidates(ctx any, fqdn any) *MockMatchAdvisor_Candidates_Call {
	return &MockMatchAdvisor_Candidates_Call{Call: _e.mock.On("Candidates", ctx, fqdn)}
}

func (_c *MockMatchAdvisor_Candidates_Call) Run(run func(ctx context.Context, fqdn string)) *MockMatchAdvisor_Candidates_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockMatchAdvisor_Candidates_Call) Return(hostIDs []domain.HostID, err error) *MockMatchAdvisor_Candidates_Call {
	_c.Call.Return(hostIDs, err)
	return _c
}

func (_c *MockMatchAdvisor_Candidates_Call) RunAndReturn(run func(ctx context.Context, fqdn string) ([]domain.HostID, error)) *MockMatchAdvisor_Candidates_Call {
	_c.Call.Return(run)
	return _c
}
