// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockModuleRepository creates a new instance of MockModuleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockModuleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockModuleRepository {
	mock := &MockModuleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockModuleRepository is an autogenerated mock type for the ModuleRepository type
type MockModuleRepository struct {
	mock.Mock
}

type MockModuleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockModuleRepository) EXPECT() *MockModuleRepository_Expecter {
	return &MockModuleRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockModuleRepository
func (_mock *MockModuleRepository) Delete(ctx context.Context, id domain.ModuleID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ModuleID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockModuleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockModuleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ModuleID
func (_e *MockModuleRepository_Expecter) Delete(ctx any, id any) *MockModuleRepository_Delete_Call {
	return &MockModuleRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockModuleRepository_Delete_Call) Run(run func(ctx context.Context, id domain.ModuleID)) *MockModuleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ModuleID
		if args[1] != nil {
			arg1 = args[1].(domain.ModuleID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModuleRepository_Delete_Call) Return(err error) *MockModuleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockModuleRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.ModuleID) error) *MockModuleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockModuleRepository
func (_mock *MockModuleRepository) Load(ctx context.Context, id domain.ModuleID) (*domain.Module, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *domain.Module
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ModuleID) (*domain.Module, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.ModuleID) *domain.Module); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Module)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.ModuleID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockModuleRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockModuleRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.ModuleID
func (_e *MockModuleRepository_Expecter) Load(ctx any, id any) *MockModuleRepository_Load_Call {
	return &MockModuleRepository_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockModuleRepository_Load_Call) Run(run func(ctx context.Context, id domain.ModuleID)) *MockModuleRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.ModuleID
		if args[1] != nil {
			arg1 = args[1].(domain.ModuleID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModuleRepository_Load_Call) Return(module *domain.Module, err error) *MockModuleRepository_Load_Call {
	_c.Call.Return(module, err)
	return _c
}

func (_c *MockModuleRepository_Load_Call) RunAndReturn(run func(ctx context.Context, id domain.ModuleID) (*domain.Module, error)) *MockModuleRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockModuleRepository
func (_mock *MockModuleRepository) Save(ctx context.Context, m *domain.Module) error {
	ret := _mock.Called(ctx, m)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Module) error); ok {
		r0 = returnFunc(ctx, m)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockModuleRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockModuleRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - m *domain.Module
func (_e *MockModuleRepository_Expecter) Save(ctx any, m any) *MockModuleRepository_Save_Call {
	return &MockModuleRepository_Save_Call{Call: _e.mock.On("Save", ctx, m)}
}

func (_c *MockModuleRepository_Save_Call) Run(run func(ctx context.Context, m *domain.Module)) *MockModuleRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Module
		if args[1] != nil {
			arg1 = args[1].(*domain.Module)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockModuleRepository_Save_Call) Return(err error) *MockModuleRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockModuleRepository_Save_Call) RunAndReturn(run func(ctx context.Context, m *domain.Module) error) *MockModuleRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
