// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockOutbox creates a new instance of MockOutbox. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutbox(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutbox {
	mock := &MockOutbox{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutbox is an autogenerated mock type for the Outbox type
type MockOutbox struct {
	mock.Mock
}

type MockOutbox_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutbox) EXPECT() *MockOutbox_Expecter {
	return &MockOutbox_Expecter{mock: &_m.Mock}
}

// Append provides a mock function for the type MockOutbox
func (_mock *MockOutbox) Append(ctx context.Context, events []domain.EventEnvelope) error {
	ret := _mock.Called(ctx, events)

	if len(ret) == 0 {
		panic("no return value specified for Append")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []domain.EventEnvelope) error); ok {
		r0 = returnFunc(ctx, events)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockOutbox_Append_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Append'
type MockOutbox_Append_Call struct {
	*mock.Call
}

// Append is a helper method to define mock.On call
//   - ctx context.Context
//   - events []domain.EventEnvelope
func (_e *MockOutbox_Expecter) Append(ctx any, events any) *MockOutbox_Append_Call {
	return &MockOutbox_Append_Call{Call: _e.mock.On("Append", ctx, events)}
}

func (_c *MockOutbox_Append_Call) Run(run func(ctx context.Context, events []domain.EventEnvelope)) *MockOutbox_Append_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []domain.EventEnvelope
		if args[1] != nil {
			arg1 = args[1].([]domain.EventEnvelope)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockOutbox_Append_Call) Return(err error) *MockOutbox_Append_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockOutbox_Append_Call) RunAndReturn(run func(ctx context.Context, events []domain.EventEnvelope) error) *MockOutbox_Append_Call {
	_c.Call.Return(run)
	return _c
}
