// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/gwall-e/services/inventory/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRackRepository creates a new instance of MockRackRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRackRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRackRepository {
	mock := &MockRackRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRackRepository is an autogenerated mock type for the RackRepository type
type MockRackRepository struct {
	mock.Mock
}

type MockRackRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRackRepository) EXPECT() *MockRackRepository_Expecter {
	return &MockRackRepository_Expecter{mock: &_m.Mock}
}

// Delete provides a mock function for the type MockRackRepository
func (_mock *MockRackRepository) Delete(ctx context.Context, id domain.RackID) error {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RackID) error); ok {
		r0 = returnFunc(ctx, id)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRackRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockRackRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.RackID
func (_e *MockRackRepository_Expecter) Delete(ctx any, id any) *MockRackRepository_Delete_Call {
	return &MockRackRepository_Delete_Call{Call: _e.mock.On("Delete", ctx, id)}
}

func (_c *MockRackRepository_Delete_Call) Run(run func(ctx context.Context, id domain.RackID)) *MockRackRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RackID
		if args[1] != nil {
			arg1 = args[1].(domain.RackID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRackRepository_Delete_Call) Return(err error) *MockRackRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRackRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id domain.RackID) error) *MockRackRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// Load provides a mock function for the type MockRackRepository
func (_mock *MockRackRepository) Load(ctx context.Context, id domain.RackID) (*domain.Rack, error) {
	ret := _mock.Called(ctx, id)

	if len(ret) == 0 {
		panic("no return value specified for Load")
	}

	var r0 *domain.Rack
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RackID) (*domain.Rack, error)); ok {
		return returnFunc(ctx, id)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, domain.RackID) *domain.Rack); ok {
		r0 = returnFunc(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Rack)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, domain.RackID) error); ok {
		r1 = returnFunc(ctx, id)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRackRepository_Load_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Load'
type MockRackRepository_Load_Call struct {
	*mock.Call
}

// Load is a helper method to define mock.On call
//   - ctx context.Context
//   - id domain.RackID
func (_e *MockRackRepository_Expecter) Load(ctx any, id any) *MockRackRepository_Load_Call {
	return &MockRackRepository_Load_Call{Call: _e.mock.On("Load", ctx, id)}
}

func (_c *MockRackRepository_Load_Call) Run(run func(ctx context.Context, id domain.RackID)) *MockRackRepository_Load_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 domain.RackID
		if args[1] != nil {
			arg1 = args[1].(domain.RackID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRackRepository_Load_Call) Return(rack *domain.Rack, err error) *MockRackRepository_Load_Call {
	_c.Call.Return(rack, err)
	return _c
}

func (_c *MockRackRepository_Load_Call) RunAndReturn(run func(ctx context.Context, id domain.RackID) (*domain.Rack, error)) *MockRackRepository_Load_Call {
	_c.Call.Return(run)
	return _c
}

// Save provides a mock function for the type MockRackRepository
func (_mock *MockRackRepository) Save(ctx context.Context, r *domain.Rack) error {
	ret := _mock.Called(ctx, r)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *domain.Rack) error); ok {
		r0 = returnFunc(ctx, r)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRackRepository_Save_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Save'
type MockRackRepository_Save_Call struct {
	*mock.Call
}

// Save is a helper method to define mock.On call
//   - ctx context.Context
//   - r *domain.Rack
func (_e *MockRackRepository_Expecter) Save(ctx any, r any) *MockRackRepository_Save_Call {
	return &MockRackRepository_Save_Call{Call: _e.mock.On("Save", ctx, r)}
}

func (_c *MockRackRepository_Save_Call) Run(run func(ctx context.Context, r *domain.Rack)) *MockRackRepository_Save_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *domain.Rack
		if args[1] != nil {
			arg1 = args[1].(*domain.Rack)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockRackRepository_Save_Call) Return(err error) *MockRackRepository_Save_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRackRepository_Save_Call) RunAndReturn(run func(ctx context.Context, r *domain.Rack) error) *MockRackRepository_Save_Call {
	_c.Call.Return(run)
	return _c
}
